// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	task_models "toDoList/internal/domain/task/task_models"

	user_models "toDoList/internal/domain/user/user_models"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: newTask
func (_m *Storage) AddTask(newTask task_models.Task) error {
	ret := _m.Called(newTask)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(task_models.Task) error); ok {
		r0 = rf(newTask)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTask provides a mock function with given fields: taskID, userID
func (_m *Storage) DeleteTask(taskID string, userID string) error {
	ret := _m.Called(taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(taskID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: userID
func (_m *Storage) DeleteUser(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTasks provides a mock function with given fields: userID
func (_m *Storage) GetAllTasks(userID string) ([]task_models.Task, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []task_models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]task_models.Task, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []task_models.Task); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task_models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsers provides a mock function with no fields
func (_m *Storage) GetAllUsers() ([]user_models.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []user_models.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]user_models.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []user_models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user_models.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: taskID, userID
func (_m *Storage) GetTaskByID(taskID string, userID string) (task_models.Task, error) {
	ret := _m.Called(taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 task_models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (task_models.Task, error)); ok {
		return rf(taskID, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) task_models.Task); ok {
		r0 = rf(taskID, userID)
	} else {
		r0 = ret.Get(0).(task_models.Task)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(taskID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *Storage) GetUserByEmail(email string) (user_models.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 user_models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (user_models.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) user_models.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(user_models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: userID
func (_m *Storage) GetUserByID(userID string) (user_models.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 user_models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (user_models.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) user_models.User); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(user_models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUser provides a mock function with given fields: user
func (_m *Storage) SaveUser(user user_models.User) (user_models.User, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 user_models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(user_models.User) (user_models.User, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(user_models.User) user_models.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(user_models.User)
	}

	if rf, ok := ret.Get(1).(func(user_models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskAttributes provides a mock function with given fields: task
func (_m *Storage) UpdateTaskAttributes(task task_models.Task) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskAttributes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(task_models.Task) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: user
func (_m *Storage) UpdateUser(user user_models.User) (user_models.User, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 user_models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(user_models.User) (user_models.User, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(user_models.User) user_models.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(user_models.User)
	}

	if rf, ok := ret.Get(1).(func(user_models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
