// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	auth "toDoList/internal/server/auth/user_auth"

	jwt "github.com/golang-jwt/jwt/v5"

	mock "github.com/stretchr/testify/mock"
)

// TokenSigner is an autogenerated mock type for the TokenSigner type
type TokenSigner struct {
	mock.Mock
}

// GetAudience provides a mock function with no fields
func (_m *TokenSigner) GetAudience() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAudience")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetIssuer provides a mock function with no fields
func (_m *TokenSigner) GetIssuer() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIssuer")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewAccessToken provides a mock function with given fields: userID
func (_m *TokenSigner) NewAccessToken(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for NewAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshToken provides a mock function with given fields: userID
func (_m *TokenSigner) NewRefreshToken(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for NewRefreshToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseAccessToken provides a mock function with given fields: token, opt
func (_m *TokenSigner) ParseAccessToken(token string, opt auth.ParseOptions) (*auth.Claims, error) {
	ret := _m.Called(token, opt)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccessToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string, auth.ParseOptions) (*auth.Claims, error)); ok {
		return rf(token, opt)
	}
	if rf, ok := ret.Get(0).(func(string, auth.ParseOptions) *auth.Claims); ok {
		r0 = rf(token, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string, auth.ParseOptions) error); ok {
		r1 = rf(token, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseRefreshToken provides a mock function with given fields: token, opt
func (_m *TokenSigner) ParseRefreshToken(token string, opt auth.ParseOptions) (*jwt.RegisteredClaims, error) {
	ret := _m.Called(token, opt)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefreshToken")
	}

	var r0 *jwt.RegisteredClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string, auth.ParseOptions) (*jwt.RegisteredClaims, error)); ok {
		return rf(token, opt)
	}
	if rf, ok := ret.Get(0).(func(string, auth.ParseOptions) *jwt.RegisteredClaims); ok {
		r0 = rf(token, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.RegisteredClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string, auth.ParseOptions) error); ok {
		r1 = rf(token, opt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenSigner creates a new instance of TokenSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenSigner {
	mock := &TokenSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
